version: '3.4'

services:
  productmicroservice:
    image: productmicroservice
    build:
      context: .
      dockerfile: ProductMicroService/Dockerfile
  db:
    image: testproduktdb
    build:
      context: .
      dockerfile: Dockerfile